### ISSUE TITLE
你好，AzPainter 2.x的简体中文翻译我已在维护。

### ISSUE THREAD

**Issue by SenlinOS** [muirmok/azpainter#1]
你好，刚刚发现你的仓库更新了，所以我特地来通知你不要重复劳动。

不过我还要听下你的意见，你想接管 AzPainter  for Linux 2.x 的翻译维护吗？

我现在只做了 AzPainter  for Linux 的简体中文翻译，Azel 的其他新软件我并没有跟进翻译，

如果你想做回 AzPainter  for Linux 的简体中文翻译维护，我可以还给你。然后你要发邮件通知 Azel 。

***

这是我当初为什么要翻译维护 AzPainter  for Linux 2.x 时写的日志：[这里](https://senlinos.com/post/translated-chinese-simplified-interface-for-azpainter-2-linux/)

这是我的 AzPainter  for Linux 简体中文翻译文件的GitHub仓库：[这里](https://github.com/SenlinOS/warehouse)

**Comment by muirmok** [comment]
你好，

谢谢你的通知。

既然你已经在翻译了，那azpainter的翻译就交给你了，其他az的软件我暂时没有翻译计划。

我自己的azpainter的翻译仓库也就不继续更新了。

祝好。
